import Head from 'next/head'
import Image from 'next/image'
import Menu from './api/Menu'
import Link from 'next/link'
import blogPic from '../public/blog.jpeg'



export const getStaticProps = async () => {
	const res = await fetch('https://simple-blog-api.crew.red/posts')
	const posts = await res.json()

	return {
		props: {
			posts
		}
	}
}

export default function Home({posts}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />

      <Image src={blogPic} alt='blog Picture'/>
			{
				posts.map(post => (
					<Link href={`/posts/${post.id}`} key={post.key}>
						<a>
							<div style={{width: '80%', margin: '10px auto'}}>
								<h2>{post.title}</h2>
								<div>{post.body}</div>
							</div>
						</a>
					</Link>
				))
			}
    </div>
  )
}

